exclude: '\.tsv$|\.csv$|\.maf'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=3000']
    -   id: check-merge-conflict
    -   id: flake8
        args:
            - "--max-line-length=88"
            - "--max-complexity=18"
            - "--select=B,C,E,F,W,T4,B9"
            - "--ignore=E203,E266,E501,W503,F403,F401,E402,F405"
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
